# -*- coding: utf-8 -*-
"""speech-to-text

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152MY4n83OLnnyig6ANftnhskN2YhZVzX
"""

!pip install transformers datasets torchaudio --quiet

from google.colab import files

uploaded = files.upload()

from transformers import pipeline

# Load Whisper small model for speech recognition
pipe = pipeline(model="openai/whisper-small", task="automatic-speech-recognition")

# Use the uploaded file name here
audio_file = "Drake - Pound cake (Jay-Z).mp3"

# Transcribe with chunking for long audio
result = pipe(audio_file, chunk_length_s=30)

# Print the transcription
print("Transcribed Text:\n", result['text'])